### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by duanwent** [pat310/quick-pivot#59]
Hi,
I'm using this in an application running in node (v6.10.2), was helped by it greatly, but after the change from using `babel-polyfill` to `babel-runtime` now I get:
>TypeError: Object.values is not a function
at o (.../node_modules/quick-pivot/lib/quick-pivot.min.js:1:3952)
at i (.../node_modules/quick-pivot/lib/quick-pivot.min.js:1:4228)
at s (.../node_modules/quick-pivot/lib/quick-pivot.min.js:1:6506)
at new e (.../node_modules/quick-pivot/lib/quick-pivot.min.js:1:1158)

Upgrading to node 7 does fix the problem, is there an easier alternative?

**Comment by pat310** [comment]
Ah yea I just noticed this problem today actually.  I had removed `babel-polyfill` because you can only have one `babel-polyfill` [per project](https://medium.com/@jcse/clearing-up-the-babel-6-ecosystem-c7678a314bf3).  I'm probably using `babel-runtime` incorrectly - I'll try to figure that out.  The alternative will be to just include a polyfill specifically for `Object.value`.

Since I'm no longer using `babel-polyfill`, you could now include that in your project which would also correct this problem.  Hopefully I'll get this issue corrected soon, thanks for posting

**Comment by turnerniles** [comment]
@duanwent just curious, what are you using the library for? Also any feedback or suggestions would be helpful!

**Comment by duanwent** [comment]
Thanks! Requiring`babel-polyfill` works perfectly.

@turnerniles I'm using it to pivot some data I get from a mysql query with multiple JOINs...also tried pivoting in mysql, but writing out combination of 12 months & year by hand is tedious...and doing it through ORM kills performance. actually was sort of a last resort but this indeed helped a lot :)

**Comment by turnerniles** [comment]
Thanks @duanwent!
